title = "chatGPT Client Configuration"

[openai]
api_key = "default"

[bot]

	name = "Servant"
	stream = true
	max_tokens = 1024
	model = "gpt-3.5-turbo"
	temperature = 0.7
	top_p = 1
	n = 1
	stop = "None"

	[bot.messages]
	welcome = "Bot Initialised"
	exit = "Bye Bye!"

[user]
name = "Lord Amulya"

[cli]
	[cli.symbols]
	hr1 = "="
	hr2 = "-"
	welcome = "🤖"
	exit = "🤖"
	error = "✘"
	stop_generation = "~"
	user = "🟢"
	bot = "🟨"

	[cli.colors]
	hr1 = "#7f8c8d"
	hr2 = "#7f8c8d"
	welcome = "#69b6f8"
	exit = "#044289"
	error = "#ff0000"
	stop_generation = "#00b5e9"
	user  = "#59c703"
	bot  = "#ffdc5d"
